name: Benchmarks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Start app (background)
        run: |
          npm run build || true
          npm run start &
        env:
          PORT: 3000
      - name: Run bench
        run: |
          # wait-for-it loop to ensure the app responds before running bench
          for i in {1..60}; do
            if curl -sSf http://localhost:3000/api/bench >/dev/null 2>&1; then
              echo "endpoint ready"
              break
            fi
            echo "waiting for app... ($i)"
            sleep 1
          done
          node bench/bench-cache.js
        env:
          BENCH_FAIL_ON_SLOW: 'false'
          BENCH_API_URL: 'http://localhost:3000/api/bench'
