name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          fail-on-severity: high
          allow-ghsas: ''
